version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=ddSMU1Kf8cbyOgD3D4hfFtnkmYjwOpeA
      - DB_NAME=bd_auth
      - DB_PORT=5432
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
volumes:
  pg_data:

